export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const TOKEN_USER_START = "TOKEN_USER_START";
export const TOKEN_USER_SUCCESS = "TOKEN_USER_SUCCESS";
export const TOKEN_USER_FAIL = "TOKEN_USER_FAIL";
