export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_START = "REGISTER_START";
export const LOGIN_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_FAIL = "REGISTER_FAIL";
