
GET  http://localhost:5000/users
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIxLCJuYW1lIjoiTmd1eT9uIFRpP24gVMOgaTExMTEyIiwiZW1haWwiOiJuZ3V5ZW50aWVudGFpMTRAZ21haWwuY29tIiwiaWF0IjoxNjM4ODEyNjE1LCJleHAiOjE2Mzg4MTI2MzB9.NTYr8lCzj7HxewyRnls_sID8uqsvxejfWpw_SwgBiZ0

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Nguyễn Tiến Tài11112",
    "email": "nguyentientai14@gmail.com",
    "password": "123456",
    "confPassword":"123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "nguyentientai14@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout
