GET http://localhost:5000/users
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJNIEZpa3JpIiwiZW1haWwiOiJlbWFpbEBnbWFpbC5jb20iLCJpYXQiOjE2MzgxNTkzMzgsImV4cCI6MTYzODE1OTM1OH0.9wFKVXz5S-E9Y6Ljqxr3Uvf79qRFP_Kcv9sEDG-BVJ0
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Nguyễn Tiến Tài11111",
    "email": "nguyentientai10@gmail.com",
    "password": "123456",
    "confPassword":"123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "email@gmail.com",
    "password": "123456"
}