GET http://localhost:5000/users
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJNIEZpa3JpIiwiZW1haWwiOiJlbWFpbEBnbWFpbC5jb20iLCJpYXQiOjE2MzgxNTkzNzAsImV4cCI6MTYzODE1OTM5MH0.8AQvwL3cnKrBvPRD1Uxs9vmFXa58yA5Xu_oS77G3zSg
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Nguyễn Tiến Tài11111",
    "email": "nguyentientai10@gmail.com",
    "password": "123456",
    "confPassword":"123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "nguyentientai10@gmail.com",
    "password": "123456"
}