GET http://localhost:5000/users

###
POST http://localhost:5000/users
Content-Type: application/json
{
    "name": "Nguyễn Tiến Tài",
    "email": "nguyentientai10@gmail.com",
    "password": "123456",
    "confPassword":"123456"
}