GET http://localhost:5000/users
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm5hbWUiOiJOZ3V5P24gVGk_biBUw6BpIiwiZW1haWwiOiJuZ3V5ZW50aWVudGFpMTBAZ21haWwuY29tIiwiaWF0IjoxNjM4MTYxOTk3LCJleHAiOjE2MzgxNjIwMTJ9.JefbgqVhFf6vOrLoZjv7u7Mc7qSOGZgnKC7_Q4dG4z8

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Nguyễn Tiến Tài11111",
    "email": "nguyentientai10@gmail.com",
    "password": "123456",
    "confPassword":"123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "nguyentientai10@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/token
