GET http://localhost:5000/users

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Nguyễn Tiến Tài",
    "email": "nguyentientai10@gmail.com",
    "password": "123456",
    "confPassword":"123456"
}

###
POST http://localhost:5000/login

Content-Type: application/json
{
    "email": "nguyentientai10@gmail.com",
    "password": "$2b$10$Wwb/2iLAxBV0sYLJrM5xS.5EbMVeSMMgSS56ZHQG2nfdycfAlC1EO",
}
